// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TournamentManager.Core.Models;

#nullable disable

namespace TournamentManager.Core.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251207170005_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("TournamentManager.Core.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("MaxAge")
                        .HasColumnType("int")
                        .HasColumnName("maxAge");

                    b.Property<decimal>("MaxWeight")
                        .HasPrecision(4, 1)
                        .HasColumnType("decimal(4,1)")
                        .HasColumnName("maxWeight");

                    b.Property<int>("MinAge")
                        .HasColumnType("int")
                        .HasColumnName("minAge");

                    b.Property<decimal>("MinWeight")
                        .HasPrecision(4, 1)
                        .HasColumnType("decimal(4,1)")
                        .HasColumnName("minWeight");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("category", (string)null);
                });

            modelBuilder.Entity("TournamentManager.Core.Models.Match", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("FirstParticipantId")
                        .HasColumnType("int")
                        .HasColumnName("firstParticipantId");

                    b.Property<int>("FirstParticipantScore")
                        .HasColumnType("int")
                        .HasColumnName("firstParticipantScore");

                    b.Property<int?>("SecondParticipantId")
                        .HasColumnType("int")
                        .HasColumnName("secondParticipantId");

                    b.Property<int>("SecondParticipantScore")
                        .HasColumnType("int")
                        .HasColumnName("secondParticipantScore");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "FirstParticipantId" }, "firstParticipantId_idx");

                    b.HasIndex(new[] { "SecondParticipantId" }, "secondParticipantId_idx");

                    b.ToTable("match", (string)null);
                });

            modelBuilder.Entity("TournamentManager.Core.Models.Participant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("datetime")
                        .HasColumnName("birthday");

                    b.Property<ulong>("Gender")
                        .HasColumnType("bit(1)")
                        .HasColumnName("gender");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("name");

                    b.Property<string>("Patronymic")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("patronymic");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("phone");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("surname");

                    b.Property<decimal>("Weight")
                        .HasPrecision(4, 1)
                        .HasColumnType("decimal(4,1)")
                        .HasColumnName("weight");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("participant", (string)null);
                });

            modelBuilder.Entity("TournamentManager.Core.Models.ParticipantTournamentCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("ParticipantId")
                        .HasColumnType("int")
                        .HasColumnName("participantId");

                    b.Property<int>("TournamentCategoryId")
                        .HasColumnType("int")
                        .HasColumnName("tournamentCategoryId");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "ParticipantId" }, "participantId_idx");

                    b.HasIndex(new[] { "TournamentCategoryId" }, "tournamentCategoryId_idx");

                    b.ToTable("participant_tournament_category", (string)null);
                });

            modelBuilder.Entity("TournamentManager.Core.Models.Tournament", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("address");

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("description");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime")
                        .HasColumnName("endDate");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("name");

                    b.Property<int>("OrganizerId")
                        .HasColumnType("int")
                        .HasColumnName("organizerId");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime")
                        .HasColumnName("startDate");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "OrganizerId" }, "id_idx");

                    b.ToTable("tournament", (string)null);
                });

            modelBuilder.Entity("TournamentManager.Core.Models.TournamentCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int")
                        .HasColumnName("categoryId");

                    b.Property<int>("JudgeId")
                        .HasColumnType("int")
                        .HasColumnName("judgeId");

                    b.Property<int>("SitesNumber")
                        .HasColumnType("int")
                        .HasColumnName("sitesNumber");

                    b.Property<int>("TournamentId")
                        .HasColumnType("int")
                        .HasColumnName("tournamentId");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "CategoryId" }, "id_idx")
                        .HasDatabaseName("id_idx1");

                    b.HasIndex(new[] { "TournamentId" }, "id_idx1")
                        .HasDatabaseName("id_idx11");

                    b.HasIndex(new[] { "JudgeId" }, "judgeId_idx");

                    b.ToTable("tournament_category", (string)null);
                });

            modelBuilder.Entity("TournamentManager.Core.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("login");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("passwordHash");

                    b.Property<string>("Patronymic")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("patronymic");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("surname");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("user", (string)null);
                });

            modelBuilder.Entity("TournamentManager.Core.Models.Match", b =>
                {
                    b.HasOne("TournamentManager.Core.Models.ParticipantTournamentCategory", "FirstParticipant")
                        .WithMany("MatchFirstParticipants")
                        .HasForeignKey("FirstParticipantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("firstParticipantId");

                    b.HasOne("TournamentManager.Core.Models.ParticipantTournamentCategory", "SecondParticipant")
                        .WithMany("MatchSecondParticipants")
                        .HasForeignKey("SecondParticipantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("secondParticipantId");

                    b.Navigation("FirstParticipant");

                    b.Navigation("SecondParticipant");
                });

            modelBuilder.Entity("TournamentManager.Core.Models.ParticipantTournamentCategory", b =>
                {
                    b.HasOne("TournamentManager.Core.Models.Participant", "Participant")
                        .WithMany("ParticipantTournamentCategories")
                        .HasForeignKey("ParticipantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("participantId");

                    b.HasOne("TournamentManager.Core.Models.TournamentCategory", "TournamentCategory")
                        .WithMany("ParticipantTournamentCategories")
                        .HasForeignKey("TournamentCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("tournamentCategoryId");

                    b.Navigation("Participant");

                    b.Navigation("TournamentCategory");
                });

            modelBuilder.Entity("TournamentManager.Core.Models.Tournament", b =>
                {
                    b.HasOne("TournamentManager.Core.Models.User", "Organizer")
                        .WithMany("Tournaments")
                        .HasForeignKey("OrganizerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("organizerId");

                    b.Navigation("Organizer");
                });

            modelBuilder.Entity("TournamentManager.Core.Models.TournamentCategory", b =>
                {
                    b.HasOne("TournamentManager.Core.Models.Category", "Category")
                        .WithMany("TournamentCategories")
                        .HasForeignKey("CategoryId")
                        .IsRequired()
                        .HasConstraintName("categoryId");

                    b.HasOne("TournamentManager.Core.Models.User", "Judge")
                        .WithMany("TournamentCategories")
                        .HasForeignKey("JudgeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("judgeId");

                    b.HasOne("TournamentManager.Core.Models.Tournament", "Tournament")
                        .WithMany("TournamentCategories")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("tournamentId");

                    b.Navigation("Category");

                    b.Navigation("Judge");

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("TournamentManager.Core.Models.Category", b =>
                {
                    b.Navigation("TournamentCategories");
                });

            modelBuilder.Entity("TournamentManager.Core.Models.Participant", b =>
                {
                    b.Navigation("ParticipantTournamentCategories");
                });

            modelBuilder.Entity("TournamentManager.Core.Models.ParticipantTournamentCategory", b =>
                {
                    b.Navigation("MatchFirstParticipants");

                    b.Navigation("MatchSecondParticipants");
                });

            modelBuilder.Entity("TournamentManager.Core.Models.Tournament", b =>
                {
                    b.Navigation("TournamentCategories");
                });

            modelBuilder.Entity("TournamentManager.Core.Models.TournamentCategory", b =>
                {
                    b.Navigation("ParticipantTournamentCategories");
                });

            modelBuilder.Entity("TournamentManager.Core.Models.User", b =>
                {
                    b.Navigation("TournamentCategories");

                    b.Navigation("Tournaments");
                });
#pragma warning restore 612, 618
        }
    }
}
